version: '3.8'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    volumes:
      - ./auth_baileys:/app/auth_baileys
      - ./database:/app/database
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    # Si vous souhaitez exposer un port pour une future interface web
    # ports:
    #   - "3000:3000"
